apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |-
      input {
        beats {
            port => "9600"
        }
      }

      output {
        # You can uncomment this line to investigate the generated events by the logstash.
        stdout { codec => rubydebug }
        elasticsearch {
            hosts => "elasticsearch:9200"
            template_overwrite => false
            manage_template => false
            # The events will be stored in elasticsearch under previously defined index_prefix value.
            index => "filebeat-%{+YYYY.MM.dd}"
            sniffing => false
        }
      }
